### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nilopaim** [hikalkan/scs#19]
On the sample server I got compilation error when on "e.Client.MessageReceived" saying that "'IScsClientService' does not contains a definition for 'MessageReceived'"...

What am I missing?

````C#
        static void Server_ClientConnected(object sender, ServerClientEventArgs e)
        {
            Console.WriteLine("A new client is connected. Client Id = " + e.Client.ClientId);

            //Register to MessageReceived event to receive messages from new client
            e.Client.MessageReceived += Client_MessageReceived;
        }
````

By the way, very nice piece of software! Congratulations!

**Comment by hikalkan** [comment]
Actually, IScsClientService (https://github.com/hikalkan/scs/blob/master/src/Scs/Communication/Scs/Server/IScsServerClient.cs#L11) is derived from IMessenger (https://github.com/hikalkan/scs/blob/master/src/Scs/Communication/Scs/Communication/Messengers/IMessenger.cs#L15) which defines the MessageReceived event.

You may need to restore nuget packages, I could not understand it

**Comment by nilopaim** [comment]
Thanks for your prompt answer.

It was my fault. when I created my server on a wrong way.

I'm using Windows 10, 64 bits, Visual Studio 2015 and Scs version from the nuget package.

Again, very nice software! Congratulations and thanks for your help!
