### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by MohammedAl-Qaisi** [hikalkan/scs#20]
Is there any configuration for the server 

I deploy application on my web-server the application work smoothly in the local but when i try to access it from the web there is an error 

my server IP Address is public and add in bound rule for the port and open it for a public.

is there any extra configuration?

**Comment by hikalkan** [comment]
In the server, no configuration. But surely you should set server's IP/port in the client side. If it does not connect, there should be some firewall block.
