### ISSUE TITLE
ClientReConnecter

### ISSUE THREAD

**Issue by ganbolor** [hikalkan/scs#25]
use ClientReConnecter example?
i use sample IrcChatSystem
how to use in sample IrcChatSystem
//Create a reconnecter to reconnect automatically on disconnect.
var reconnecter = new ClientReConnecter(_scsClient) {ReConnectCheckPeriod = 30000};

**Comment by hikalkan** [comment]
Using ClientReConnecter is very simple (as you have written in the question). Could not understand the exact question.
